### ISSUE TITLE
Why is there no pricing on your website?

### ISSUE THREAD

**Issue by nkev** [cipherstash/tandem-getting-started#1]
Why is there no pricing on your website?

**Comment by calvinbrewer** [comment]
Hey @nkev - we charge based on the number of data keys  (number of records in your database) used for encryption. As a customer centric organization, we are keen to chat with people who want to use the technology and work through a pricing model that works for both parties. 

Full transparency, we will eventually be posting pricing on the website.

**Comment by nkev** [comment]
> ...people who want to use the technology

But you're losing potential customers. People cannot know if they want to use the technology unless they know they can afford it. Potential customers should not be forced to contact every company just for pricing. This is a terrible first impression, no matter how good a product is!

**Comment by coderdan** [comment]
Hey @nkev, I don't disagree! We've been operating in a preview mode for our Tandem product and are planning to release official pricing soon. It will be public and transparent and our aim is to make it as simple as possible.
